%%
clear;
parpool(12);
%%
run_experiment_semi('norb',1)
%%
run_experiment_semi('norb',5)
%%
run_experiment_semi('norb',8)
%%
run_experiment_semi('norb',10)
%%
run_experiment_semi('norb',15)
%%
run_experiment_semi('aloi',1)
%%
run_experiment_semi('aloi',5)
%%
run_experiment_semi('aloi',8)
%%
run_experiment_semi('aloi',10)
%%
run_experiment_semi('aloi',15)
%%
run_experiment_semi('rcv1',1)
%%
run_experiment_semi('rcv1',5)
%%
run_experiment_semi('rcv1',8)
%%
run_experiment_semi('rcv1',10)
%%
run_experiment_semi('rcv1',15)
%%
run_experiment_semi('mnist630k',1)
%%
run_experiment_semi('mnist630k',5)
%%
run_experiment_semi('mnist630k',8)
%%
run_experiment_semi('mnist630k',10)
%%
run_experiment_semi('mnist630k',15)
%%
run_experiment_semi('cifar10-rgb',1)
%%
run_experiment_semi('cifar10-rgb',5)
%%
run_experiment_semi('cifar10-rgb',8)
%%
run_experiment_semi('cifar10-rgb',10)
%%
run_experiment_semi('cifar10-rgb',15)
%%
run_experiment_semi('covtype',1)
%%
run_experiment_semi('covtype',5)
%%
run_experiment_semi('covtype',8)
%%
run_experiment_semi('covtype',10)
%%
run_experiment_semi('covtype',15)
%%
run_experiment_semi('covtype',50)
%%
run_experiment_semi('covtype',100)
%%
run_experiment_semi('usps-large',1)
%%
run_experiment_semi('usps-large',5)
%%
run_experiment_semi('usps-large',8)
%%
run_experiment_semi('usps-large',10)
%%
run_experiment_semi('usps-large',15)
%%
run_experiment_semi('mnist-large-imbalance',1)
%%
run_experiment_semi('mnist-large-imbalance',5)
%%
run_experiment_semi('mnist-large-imbalance',8)
%%
run_experiment_semi('mnist-large-imbalance',10)
%%
run_experiment_semi('mnist-large-imbalance',15)